const express = require("express")
const authMiddleware = require("../middlewares/auth.middleware")
const interviewController = require("../controllers/interview.controller")
const upload = require("../middlewares/file.middleware")
const interviewRouter = express.Router()

interviewRouter.post("/", authMiddleware.authUser, upload.single("resume"), interviewController.generateInterViewReportController)
interviewRouter.get("/report/:interviewId", authMiddleware.authUser, interviewController.getInterviewReportByIdController)
interviewRouter.get("/", authMiddleware.authUser, interviewController.getAllInterviewReportsController)
interviewRouter.post("/resume/pdf/:interviewReportId", authMiddleware.authUser, interviewController.generateResumePdfController)
interviewRouter.get("/resume/:interviewReportId/versions", authMiddleware.authUser, interviewController.getResumeVersionsController)
interviewRouter.post("/resume/:interviewReportId/draft", authMiddleware.authUser, interviewController.generateResumeDraftController)
interviewRouter.post("/resume/:interviewReportId/versions", authMiddleware.authUser, interviewController.saveResumeVersionController)
interviewRouter.post("/resume/:interviewReportId/export", authMiddleware.authUser, interviewController.exportEditedResumePdfController)
module.exports = interviewRouter
