import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router';
import {createApplication,getApplications,updateApplication,deleteApplication} from '../services/application.api';
import {getAllInterviewReports} from '../../interview/services/interview.api';
import './tracker.scss';

const empty={company:'',role:'',status:'Saved',deadline:'',notes:'',interviewReport:''};
export default function ApplicationTracker(){
 const navigate=useNavigate(); const [apps,setApps]=useState([]); const [reports,setReports]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [error,setError]=useState('');
 const load=async()=>{const [a,r]=await Promise.all([getApplications(),getAllInterviewReports()]);setApps(a.applications||[]);setReports(r.interviewReports||[])};
 useEffect(()=>{Promise.resolve().then(load).catch(e=>setError(e.response?.data?.message||'Unable to load applications.'))},[]);
 const submit=async e=>{e.preventDefault();setError('');try{const payload={...form,deadline:form.deadline||undefined,interviewReport:form.interviewReport||undefined}; if(editing) await updateApplication(editing,payload); else await createApplication(payload);setForm(empty);setEditing(null);await load()}catch(e){setError(e.response?.data?.message||'Unable to save application.')}};
 const remove=async id=>{if(!window.confirm('Delete this application?'))return;await deleteApplication(id);setApps(v=>v.filter(a=>a._id!==id))};
 return <main className='tracker-page'><header className='tracker-header'><div><button className='text-button' onClick={()=>navigate('/')}>← Home</button><h1>Application Tracker</h1><p>Keep your applications, deadlines and interview reports in one place.</p></div></header>{error&&<p className='tracker-error'>{error}</p>}
 <section className='tracker-layout'><form className='tracker-form' onSubmit={submit}><h2>{editing?'Edit application':'Add application'}</h2><input placeholder='Company *' value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><input placeholder='Role *' value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['Saved','Applied','Interview','Offer','Rejected','Withdrawn'].map(s=><option key={s}>{s}</option>)}</select><label>Deadline<input type='date' value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label><select value={form.interviewReport} onChange={e=>setForm({...form,interviewReport:e.target.value})}><option value=''>Link interview report</option>{reports.map(r=><option key={r._id} value={r._id}>{r.title}</option>)}</select><textarea placeholder='Notes' value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className='primary'>{editing?'Update':'Save application'}</button>{editing&&<button type='button' onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</form>
 <section className='application-list'>{apps.length===0?<div className='empty'>No applications yet.</div>:apps.map(a=><article className='application-card' key={a._id}><div><h2>{a.company}</h2><p>{a.role}</p></div><span className={`status status--${a.status.toLowerCase()}`}>{a.status}</span><div className='application-meta'><span>Deadline: {a.deadline?new Date(a.deadline).toLocaleDateString():'—'}</span>{a.interviewReport&&<button className='link-button' onClick={()=>navigate(`/interview/${a.interviewReport._id}`)}>Report: {a.interviewReport.title}</button>}</div>{a.notes&&<p className='notes'>{a.notes}</p>}<div className='card-actions'><button onClick={()=>{setEditing(a._id);setForm({company:a.company,role:a.role,status:a.status,deadline:a.deadline?a.deadline.slice(0,10):'',notes:a.notes||'',interviewReport:a.interviewReport?._id||''})}}>Edit</button><button onClick={()=>remove(a._id)}>Delete</button></div></article>)}</section></section></main>;
}
